os: linux
language: haskell

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

ghc:
  - 8.2

install:
  - cabal update
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test --show-details=direct